# Example YAML configuration
substitutions:
  name: mppt-controller
  device_description: "Monitor and control a MPPT Charge Controller via UART"
  rx_pin: GPIO17
  tx_pin: GPIO16

esphome:
  name: ${name}
  comment: ${device_description}

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  ap:
    ssid: "MPPT Fallback Hotspot"
    password: !secret fallback_password

ota:
  - platform: esphome
    password: !secret ota_password

external_components:
  - source: github://Mr-EJ/art-mppt-controller

uart:
  - id: mppt_bus
    tx_pin: ${tx_pin}
    rx_pin: ${rx_pin}
    baud_rate: 9600

mppt_controller:
  id: mppt1
  update_interval: 5s

  pv_voltage:
    name: "PV Voltage"
  pv_current:
    name: "PV Current"
  battery_voltage:
    name: "Battery Voltage"
  temperature:
    name: "Battery Temperature"
  load_current:
    name: "Load Current"
  daily_energy:
    name: "Daily Energy"
  total_energy:
    name: "Total Energy"

  load_switch:
    name: "MPPT Load Output"

script:
  - id: reset_mppt_energy
    then:
      - mppt_controller.reset_energy:
          clear: true
          reboot: false

  - id: set_mppt_params
    then:
      - mppt_controller.set_charging_params:
          charge_current: 16
          battery_type: 4
          const_voltage: 288
          load_undervoltage: 224
