# Example YAML configuration
substitutions:
  name: mpptcontrol
  device_description: "Monitor and control a MPPT Charge Controller via UART"
  rx_pin: GPIO17
  tx_pin: GPIO16

esphome:
  name: ${name}
  comment: ${device_description}


esp32:
  board: esp32dev
  framework:
    type: esp-idf

# web_server:
#   port: 80

logger:

# Required sensor platform
sensor:

# Required switch platform (for load_switch)
switch:

# Required text_sensor for any text-based sensors
text_sensor:

# Required binary_sensor platform
binary_sensor:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
#  use_address: 192.168.0.194
  
  ap:
    ssid: "MPPT Fallback Hotspot"
    password: "fallback_password"

api:
ota:
  - platform: esphome
    password: !secret ota_password

external_components:
  - source:
      type: local
      path: .
    components: mppt_controller

uart:
  - id: mppt_bus
    tx_pin: ${tx_pin}
    rx_pin: ${rx_pin}
    baud_rate: 9600  

mppt_controller:
  id: mppt1
  update_interval: 8s

  pv_voltage:
    name: "PV Voltage"
    accuracy_decimals: 3
  pv_current:
    name: "PV Current"
    accuracy_decimals: 3
  pv_power:
    name: "PV Power"
    accuracy_decimals: 3
  battery_voltage:
    name: "Battery Voltage"
    accuracy_decimals: 3
  temperature:
    name: "MPPT Temperature"
    accuracy_decimals: 3
  load_current:
    name: "Load Current"
    accuracy_decimals: 3
  daily_energy:
    name: "Daily Energy"
    accuracy_decimals: 3
  total_energy:
    name: "Total Energy"
    accuracy_decimals: 3
  error_code:
    name: "MPPT Error Code"
  working_mode:
    name: "MPPT Working Mode"
    
  load_switch:
    name: "MPPT Load Output"
    icon: "mdi:power"
    entity_category: config
    mppt_controller: mppt1 

script:
  - id: reset_mppt_energy
    then:
      - mppt_controller.reset_energy: 
          id: mppt1
          clear: true
          reboot: false

  - id: set_mppt_params
    then:
      - mppt_controller.set_charging_params: 
          id: mppt1
          charge_current: 16
          battery_type: 4
          const_voltage: 288
          load_undervoltage: 224
